### ISSUE TITLE
Add a 'mail_domain' Env Var in the entrypoint

### ISSUE THREAD

**Issue by jabbate19** [roundcube/roundcubemail-docker#231]
Commonly, the default domain should be different than the hostname of the mail server. For example, if my mail server is `mail.jabbate19.com`, my likely mail name is `@jabbate19.com`. There is a config variable in roundcube for this named `mail_domain`, but there is no environment variable for this through Docker.

If this is a desired feature, I would be interested in adding it, but wanted to get feedback through an issue before going forward.

**Comment by jpduyx** [comment]
i am also looking for this feature ...

**Comment by thomascube** [comment]
Fixed with #240

**Comment by The-HEAD** [comment]
Hi @thomascube ,
sorry that i have to open this up again - but it seems that specific request has not been implemented and the option is still missing. 
Current Situation:
ROUNDCUBEMAIL_USERNAME_DOMAIN = mail.example.com  will add this to the username upon loging in, meaning it will try to log into the mailserver with "username@mail.example.com" which might be wrong.

What was requested is to have ROUNDCUBEMAIL_MAIL_DOMAIN = example.com , specifying the mail domain AFTER login, so that the login is with "username" and then the email is "username@example.com".

In the "docker-entrypoint.sh" we would need the following line:
  \$config['mail_domain'] = '${ROUNDCUBEMAIL_MAIL_DOMAIN}';

thank you  :)

**Comment by MahdiBaghbani** [comment]
I've also run into this problem recently, deploying the Roundcube at University, the login IDs are entirely different and without any `@whatever`, with this `ROUNDCUBEMAIL_USERNAME_DOMAIN` users can't login, without it users get wrong email address after login and have to edit manually in order to be able to send emails
